name: pet_adopt_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  go_router: ^13.0.1
  get_it: ^7.6.6
  lottie: ^2.7.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  sqflite: ^2.3.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets: 
    - assets/lottie/
    - assets/images/
